#!/usr/bin/env node
/**
 * Generates the design system's primitive colour ramps.
 *
 * The palette is computed, not picked. Every family walks the same lightness
 * scale in OKLCH, so "violet-600" and "rose-600" are the same perceptual
 * lightness — which is what makes a swap between them safe, and what makes the
 * contrast results below predictable instead of lucky.
 *
 * Chroma is reduced per step until the colour is inside sRGB, so a vivid hue
 * degrades gracefully at the ends of the ramp rather than clipping to a
 * different colour than the one requested.
 *
 *   node scripts/generate-palette.mjs > src/ds/tokens/primitives.css
 */

/** Perceptual lightness for each step. Shared by every family. */
const STEPS = [
  [50, 0.985],
  [100, 0.96],
  [200, 0.915],
  [300, 0.85],
  [400, 0.765],
  [500, 0.68],
  [600, 0.59],
  [700, 0.5],
  [800, 0.4],
  [900, 0.29],
  [950, 0.19],
];

/** Hue in degrees, and the chroma the family aims for at mid-lightness. */
const FAMILIES = [
  ["slate", 252, 0.014],
  ["violet", 292, 0.17],
  ["sky", 232, 0.14],
  ["emerald", 158, 0.13],
  ["amber", 76, 0.15],
  ["rose", 22, 0.16],
];

const clamp01 = (v) => Math.min(1, Math.max(0, v));

/** OKLCH -> linear sRGB. Björn Ottosson's matrices. */
function oklchToLinearRgb(L, C, hDeg) {
  const h = (hDeg * Math.PI) / 180;
  const a = C * Math.cos(h);
  const b = C * Math.sin(h);

  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;

  const l = l_ ** 3;
  const m = m_ ** 3;
  const s = s_ ** 3;

  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}

const inGamut = ([r, g, b]) =>
  [r, g, b].every((v) => v >= -0.0001 && v <= 1.0001);

const encode = (v) => {
  const c = clamp01(v);
  const srgb = c <= 0.0031308 ? c * 12.92 : 1.055 * c ** (1 / 2.4) - 0.055;
  return Math.round(srgb * 255);
};

const toHex = (rgb) =>
  "#" + rgb.map((v) => encode(v).toString(16).padStart(2, "0")).join("");

/**
 * Chroma is highest in the middle of the ramp and tapers at both ends — a
 * near-white or near-black that keeps full saturation reads as a tint, not as
 * the same family. Then it is reduced further until the result is displayable.
 */
function swatch(L, targetChroma, hue) {
  const taper = 1 - Math.abs(L - 0.6) / 0.62;
  let chroma = targetChroma * Math.max(0.18, taper);

  for (let i = 0; i < 200; i++) {
    const rgb = oklchToLinearRgb(L, chroma, hue);
    if (inGamut(rgb)) return toHex(rgb);
    chroma *= 0.97;
  }
  return toHex(oklchToLinearRgb(L, 0, hue));
}

const lines = [
  "/* GENERATED by scripts/generate-palette.mjs — do not edit by hand.",
  " *",
  " * Primitive ramps. These are named for what they ARE. Nothing in a component",
  " * may reference them directly; components read the semantic layer, which is",
  " * what makes a theme swap a remap instead of a rewrite.",
  " */",
  ":root {",
];

for (const [name, hue, chroma] of FAMILIES) {
  for (const [step, L] of STEPS) {
    lines.push(`  --ds-${name}-${step}: ${swatch(L, chroma, hue)};`);
  }
  lines.push("");
}

lines[lines.length - 1] = "}";
console.log(lines.join("\n"));
